name: HDV
version: '${project.version}'
main: fr.yohem.hdv.HDV
depend:
  - Vault
commands:
  hdv open:
    description: access a l'hdv
    usages: Mauvais utilisation de la commande.
    permission: hdv.commands.open
    aliases:
      - hdv o
  hdv sell:
    description: access a l'hdv
    usages: Mauvais utilisation de la commande.
    permission: hdv.commands.sell
    aliases:
      - hdv s
  hdv admin:
    description: access a l'hdv
    usages: Mauvais utilisation de la commande.
    permission: hdv.commands.admin
    aliases:
      - hdv a
  hdv whitelist:
    description: access a l'hdv
    usages: Mauvais utilisation de la commande.
    permission: hdv.commands.whitelist
    aliases:
      - hdv w
  hdv home:
    description: access a l'hdv
    usages: Mauvais utilisation de la commande.
    permission: hdv.commands.use
    aliases:
      - hdv
      - hdv h
permissions:
  hdv.commands.help:
    description: acces to hdv help
    default: true
  hdv.commands.use:
    description: acces to hdv
    default: true
    children:
      hdv.commands.sell: true
      hdv.commands.buy: true
  hdv.commands.sell:
    description: access to sell item in hdv
    default: true
  hdv.use.buy:
    description: access to buy item in hdv
    default: true
  hdv.commands.whitelist:
    default: op
    description: enable item on whitelist
    children:
      hdv.commands.use: true
  hdv.commands.admin:
    default: op
    description: access  administrator maneger hdv menu
    children:
      hdv.commands.use: true
      hdv.commands.whitelist: true
      hdv.commands.see: true
      hdv.commands.open: true

  hdv.commands.see:
    default: op
    description: access to see item in shop of an seller
  hdv.commands.open:
    description: force an player to open hdv
    default: op
